[tool.poetry]
name = "flist-rich"
version = "0.1.0"
description = ""
authors = ["Ka'vi"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "^3.10"
rich = "^12.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
